# This will appear before many messages from the plugin.
message-prefix: '&8[&7Waygates&8]'

# Use a minecraft colour code here to pick the message colour
message-colour: '7'

# The highlight colour (to complement the above colour)
highlight-colour: 'b'

# Errors will be this colour.
error-colour: 'c'

# Error highlights
error-highlight: '8'

# When enabled, players will be forced to respect the fog by showing block displays to the player
# to limit their view distance, instead of world fog which can often be disabled in video settings or via mods.
fake-fog:
  enabled: false
  # TODO: Add more stuff here lol